<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PatternEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatternEventRepository extends EntityRepository
{
}
